// AUTO-GENERATED BY `generate-icons-map.ts`
// Run the generator script to update this file.

import Add from "./icon-add.svelte"
import ArrowBack from "./icon-arrow-back.svelte"
import ArrowDropdown from "./icon-arrow-dropdown.svelte"
import ArrowExternal from "./icon-arrow-external.svelte"
import ArrowForward from "./icon-arrow-forward.svelte"
import AvatarAnon from "./icon-avatar-anon.svelte"
import AvatarSigned from "./icon-avatar-signed.svelte"
import Cancel from "./icon-cancel.svelte"
import Copy from "./icon-copy.svelte"
import DoomeyeClosed from "./icon-doomeye-closed.svelte"
import Doomeye from "./icon-doomeye.svelte"
import Filter from "./icon-filter.svelte"
import Hamburger from "./icon-hamburger.svelte"
import Help from "./icon-help.svelte"
import Home from "./icon-home.svelte"
import Link from "./icon-link.svelte"
import Mail from "./icon-mail.svelte"
import Purchase from "./icon-purchase.svelte"
import Remove from "./icon-remove.svelte"
import Search from "./icon-search.svelte"
import Settings from "./icon-settings.svelte"
import Starmark from "./icon-starmark.svelte"
import Upload from "./icon-upload.svelte"

const ICONS = {
	Add,
	ArrowBack,
	ArrowDropdown,
	ArrowExternal,
	ArrowForward,
	AvatarAnon,
	AvatarSigned,
	Cancel,
	Copy,
	DoomeyeClosed,
	Doomeye,
	Filter,
	Hamburger,
	Help,
	Home,
	Link,
	Mail,
	Purchase,
	Remove,
	Search,
	Settings,
	Starmark,
	Upload,
} as const

export type DoomscrllIcon = keyof typeof ICONS

export function getDoomscrllIcon(name: DoomscrllIcon) {
  return ICONS[name]
}

export function getAllDoomscrllIcons() {
  return Object.keys(ICONS)
}
  